### ISSUE TITLE
Aspect ratio of image

### ISSUE THREAD

**Issue by kierok** [robin-dela/hover-effect#3]
Hello. Is it possible to respect aspect ratio of image, inside of three scene. 
Or to make image behavior similar to object-fit: cover? 
For the purpose of percent width container

**Comment by jeffcorey** [comment]
Same here. Anyone figure out a solution?

**Comment by enoks** [comment]
**To keep the image ratio** you have to apply the image dimensions to `PlaneBufferGeometry` (not the parent's one).
```js
var geometry = new THREE.PlaneBufferGeometry(texture1.image.width, texture1.image.height);
```

_Unfortunately_, you have to wait until the picture is loaded before you can do that. You could use the onload callback of [TextureLoader's load method](https://threejs.org/docs/#api/loaders/TextureLoader.load) to execute the Three-stuff (material, geometry, mesh, ...).

**Next you need to adjust the camera** to show the images in correct size.
```js
// use Math.max for 'cover' or Math.min for 'contain'
camera.scale.x = camera.scale.y = 1/Math.max(
    parent.offsetWidth/texture1.image.width,
    parent.offsetHeight/textture1.image.height
);
```
**For responsive displays** and dynamic canvas size adjust camera frustum and scale:
```js
window.addEventListener( 'resize', function() {
    camera.top = parent.offsetHeight/2;
    camera.right = parent.offsetWidth/2;
    camera.bottom = parent.offsetHeight/-2;
    camera.left = parent.offsetWidth/-2;

    camera.scale.x = camera.scale.y = 1/Math.max(
        parent.offsetWidth/texture1.image.width,
        parent.offsetHeight/texture1.image.height
    );

    camera.updateProjectionMatrix();

    renderer.setSize( $parent.offsetWidth, $parent.offsetHeight );
}, false );
```

**Comment by celsowhite** [comment]
I was able to solve this with pure css. The trick is to make sure the parent container you are injecting the scene into has the images aspect ratio.

**HTML**

```html
<div class="hover-image"></div>
```
**CSS**

```css
.hover-image {
    position: relative;
}

.hover-image:after {
    content: "";
    display: block;
    padding-bottom: 130%;  // This is the essential part. Adjust this percent so it matches the images aspect ratio.
}

.hover-image canvas {
    position: absolute; // Canvas must be absolute so the padding-bottom trick works on the after pseudo element.
}
```
